.MODEL TINY
.486
.CODE
    ORG     100H
START:
	LOCK    MOV		DWORD PTR ES:[ESP+EBP*4+0101010H], 10101010H
	MOV 	DS, AX
	MOV 	SS, SP
	CWD
	MOV 	ES:[BX+SI], AL
	MOV 	BL, CL
	MOV 	CS:[BX+SI], BX
	MOV 	CX, SI
	MOV 	AL, DS:[BX+SI]
	MOV 	AX, DS:[BX+SI]
	MOV 	SS:[1000H], ES
	MOV 	AX, SS
	MOV 	EBX, FS

	MOV 	AL, GS:[10H]
	MOV 	AX, CS:[1H]
	MOV 	EAX, DS:[0ABCDEFH]
	MOV 	SS:[0AH], AL
	MOV 	GS:[1234H], AX
	MOV 	BH, 10H
	MOV 	BX, 1000H
	SAR 	byte ptr SS:[SI+100H], 10H
	SAR     CX, 0H
	SAR		EAX, 0AAH
	SAR 	word ptr FS:[EAX+ECX*8+0ABCDEFH], 0ABH
	MOV 	BYTE PTR CS:[BP+SI+1H], 1H
	MOV 	WORD PTR DS:[SI], 0H
	MOV 	DWORD PTR SS:[DI], 100H
	SAR 	dword ptr SS:[SI+100H], 1H
	SAR     CX, 1H
	SAR		EAX, 01H
	SAR 	byte ptr FS:[ECX*8+0ABCDEFH], 1H
	SAR 	word ptr SS:[BX+SI+100H], CL
	SAR     CX, CL
	SAR		EDX, CL
	SAR 	dword ptr CS:[ESP], CL
END START
